<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2d56a434-42a2-47e0-bbff-b9f54bc58222</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
	<PackageReference Include="Microsoft.OpenApi" Version="1.6.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="1.2.61" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StarkInventorySystem.Application\StarkInventorySystem.Application.csproj" />
    <ProjectReference Include="..\StarkInventorySystem.Infrastructure\StarkInventorySystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
